# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [294]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [295]:
print("NumPy version:", np.__version__)
print("NumPy configuration:", np.show_config())

NumPy version: 1.26.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/User/miniconda3/Library/include
    lib directory: C:/Users/User/miniconda3/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/User/miniconda3/Library/include
    lib directory: C:/Users/User/miniconda3/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.0
Machine Information:
  build:
   

#### 3. Create a null vector of size 10 (★☆☆)

In [296]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [297]:
memory_size_bytes = null_vector.nbytes
print("Memory size of the ",null_vector,":", memory_size_bytes, "bytes")

Memory size of the  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] : 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [298]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [299]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [300]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [301]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [302]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [303]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [304]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [305]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.29413436 0.95172791 0.81672598]
  [0.16120578 0.83398072 0.34565769]
  [0.22776817 0.78207134 0.85699805]]

 [[0.96044905 0.42021918 0.56211139]
  [0.6149172  0.6277041  0.40215607]
  [0.15235027 0.07044587 0.90598839]]

 [[0.36655103 0.18068733 0.98357201]
  [0.80290788 0.98118289 0.27880565]
  [0.46324777 0.80869298 0.5518909 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [306]:
random_array = np.random.rand(10, 10)
print(random_array)
print("Minimum:", np.min(random_array))
print("Maximum:", np.max(random_array))

[[0.35496346 0.15842659 0.56176521 0.59838735 0.72074789 0.79052573
  0.11810869 0.62795311 0.78144126 0.38900572]
 [0.27556728 0.47965547 0.3100866  0.50985482 0.30849308 0.42270161
  0.91513833 0.91660563 0.99217893 0.4861234 ]
 [0.16803881 0.88902664 0.59684329 0.74772008 0.16259419 0.31969817
  0.27521802 0.55975623 0.99717526 0.6123487 ]
 [0.57286373 0.75908264 0.32881518 0.25319129 0.83804417 0.96055156
  0.42140736 0.04126449 0.17916072 0.85698133]
 [0.12164475 0.76300622 0.62024496 0.72673305 0.25659055 0.01832994
  0.03975444 0.72484968 0.61339743 0.84045314]
 [0.39924734 0.55555135 0.78350572 0.49665059 0.99334852 0.74289172
  0.68331044 0.80153219 0.7771902  0.21969525]
 [0.21038394 0.60607426 0.43604821 0.8715766  0.29010231 0.33085945
  0.16631375 0.98174197 0.11604653 0.98289999]
 [0.70639266 0.08915139 0.15201539 0.32697117 0.26034607 0.9731283
  0.61334208 0.07438995 0.52540462 0.89713979]
 [0.41618182 0.66613056 0.77319258 0.18502902 0.85550074 0.44882116
  0.0566886  

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [307]:
random_vector = np.random.rand(30)
print("Random vector:", random_vector)
print("Mean:", np.mean(random_vector))

Random vector: [0.25046981 0.21239837 0.25115556 0.46829797 0.14627967 0.10661254
 0.75674066 0.02330167 0.38548418 0.39603441 0.89304134 0.7744911
 0.51067673 0.47981299 0.5656013  0.35782783 0.70077719 0.68607117
 0.57465465 0.05769268 0.12683766 0.03927628 0.71851573 0.47759968
 0.95498117 0.95232837 0.79817082 0.44304892 0.3163504  0.20097422]
Mean: 0.4541835020984764


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [308]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [309]:
existing_array = np.ones((3, 3)) 
new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("Existing array:")
print(existing_array)
print("\nNew:")
print(new_array)

Existing array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

New:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [310]:
print('0 * np.nan: ', 0 * np.nan)
print("np.nan == np.nan:", np.nan == np.nan)
print("np.inf > np.nan:", np.inf > np.nan)
print("np.nan - np.nan:", np.nan - np.nan)
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1: ", 0.3 == 3 * 0.1)

0 * np.nan:  nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1:  False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [311]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [312]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1  
matrix[::2, 1::2] = 1 
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [313]:

print("100th element:", np.unravel_index(99, (6,7,8)))

100th element: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [314]:
matrix = np.array([[0, 1], [1, 0]])
print(np.tile(matrix, (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [315]:
matrix = np.random.rand(5, 5)
matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(matrix,'\n')
print(matrix)

[[-0.85367266  1.7490145   0.16928369 -1.61007509 -1.50003711]
 [-0.07656115 -0.12905435 -0.25929822  1.17644441  0.76277471]
 [-1.28324273 -0.40656572  0.39709301 -0.33852984 -0.93674996]
 [ 0.50484126  0.41622012  1.69506308  0.2747945   1.35054967]
 [ 1.60778323 -0.15892632 -1.47049935 -1.15933817  0.07868848]] 

[[-0.85367266  1.7490145   0.16928369 -1.61007509 -1.50003711]
 [-0.07656115 -0.12905435 -0.25929822  1.17644441  0.76277471]
 [-1.28324273 -0.40656572  0.39709301 -0.33852984 -0.93674996]
 [ 0.50484126  0.41622012  1.69506308  0.2747945   1.35054967]
 [ 1.60778323 -0.15892632 -1.47049935 -1.15933817  0.07868848]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [316]:
dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [317]:
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)
print("5x3 Matrix:")
print(matrix_5x3)
print("\n3x2 Matrix:")
print(matrix_3x2)
print("\n5x3 * 3x2:")
print(np.dot(matrix_5x3, matrix_3x2))

5x3 Matrix:
[[0.892958   0.65413207 0.20148172]
 [0.70104435 0.89421932 0.03022556]
 [0.24281212 0.15318082 0.784103  ]
 [0.89147741 0.55455748 0.84820187]
 [0.65693716 0.65669954 0.57970817]]

3x2 Matrix:
[[0.0500187  0.93697811]
 [0.35577143 0.80257771]
 [0.80998457 0.96576123]]

5x3 * 3x2:
[[0.44058318 1.55625714]
 [0.37768525 1.40373437]
 [0.70175384 1.10770544]
 [0.92891667 2.09953076]
 [0.73604875 1.70244783]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [318]:
array = np.array([1, 4, 6, 9, 3, 5, 7, 2, 8])
print(array)
array[(array >= 3) & (array <= 8)] *= -1
print(array)

[1 4 6 9 3 5 7 2 8]
[ 1 -4 -6  9 -3 -5 -7  2 -8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [319]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.int32' object is not callable

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = [1, 2, 3]
result_1 = [2 << val >> 2 for val in Z]
result_2 = [1j * val for val in Z]
result_3 = [val / 1 / 1 for val in Z]
print("2 << Z >> 2 is legal:", result_1)  
print("1j*Z is legal:", result_2) 
print("Z/1/1 is legal:", result_3)


2 << Z >> 2 is legal: [1, 2, 4]
1j*Z is legal: [1j, 2j, 3j]
Z/1/1 is legal: [1.0, 2.0, 3.0]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print("np.array(0) / np.array(0):", np.array(0) / np.array(0)) 
print("np.array(0) // np.array(0):", np.array(0) // np.array(0)) 
print("np.array([np.nan]).astype(int).astype(float):",np.array([np.nan]).astype(int).astype(float))


np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [-2.14748365e+09]


C:\Users\User\AppData\Local\Temp\ipykernel_5220\3442397122.py:1: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
C:\Users\User\AppData\Local\Temp\ipykernel_5220\3442397122.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
C:\Users\User\AppData\Local\Temp\ipykernel_5220\3442397122.py:3: RuntimeWarning: invalid value encountered in cast
  print("np.array([np.nan]).astype(int).astype(float):",np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
float_array = np.array([2.3, 5.8, 6.5, -7.2, 9.1, -1.5])
rounded_array = np.where(float_array >= 0, np.ceil(float_array), np.floor(float_array))
print("float array:")
print(float_array)
print("\nRounded array:")
print(rounded_array)

float array:
[ 2.3  5.8  6.5 -7.2  9.1 -1.5]

Rounded array:
[ 3.  6.  7. -8. 10. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
print("Array 1:", array1)
print("Array 2:", array2)
print("\nCommon values:", np.intersect1d(array1, array2))

Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]

Common values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# import warnings

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.isclose(np.sqrt(-1), np.emath.sqrt(-1)))

False


C:\Users\User\AppData\Local\Temp\ipykernel_5220\3893968646.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isclose(np.sqrt(-1), np.emath.sqrt(-1)))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today')
print("Yesterday:", today - np.timedelta64(1, 'D'))
print("Today:", today)
print("Tomorrow:", today + np.timedelta64(1, 'D'))

Yesterday: 2023-12-07
Today: 2023-12-08
Tomorrow: 2023-12-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("Dates:")
print(dates)

Dates:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3], dtype='float64')
B = np.array([4, 5, 6])
np.add(A, B, out=A) 
np.negative(A, out=A) 
np.divide(A, 2, out=A) 
np.multiply(A, B, out=A) 
result = A  
print(result)

[-10.  -17.5 -27. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
array = np.random.rand(5) * 10
print(array - array%1)
print(np.floor(array))
print(array.astype(int))
print(np.trunc(array))

[7. 3. 3. 3. 9.]
[7. 3. 3. 3. 9.]
[7 3 3 3 9]
[7. 3. 3. 3. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros((5, 5)) + np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate_integers():
    for i in range(10):
        yield i
generated_array = np.fromiter(generate_integers(), dtype=int, count=10)
print(generated_array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.rand(10)
print("Vector:")
print(vector)
print("\nSorted vector:")
print(np.sort(vector))

Vector:
[0.45201007 0.29110331 0.78094031 0.07991996 0.22550055 0.96287903
 0.65723568 0.0975282  0.06049567 0.071382  ]

Sorted vector:
[0.06049567 0.071382   0.07991996 0.0975282  0.22550055 0.29110331
 0.45201007 0.65723568 0.78094031 0.96287903]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
array = np.random.rand(100)
sum(array)

46.56974794795598

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(5)
B = np.random.rand(5)
print("Array A:", A)
print("Array B:", B)
print("\nAre arrays A and B equal?", np.allclose(A, B))

Array A: [0.93963565 0.03817123 0.98407449 0.86470932 0.20770993]
Array B: [0.22389885 0.03862548 0.48667414 0.66309143 0.17819019]

Are arrays A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1.flags.writeable = False
arr1[2] = 0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
matrix = np.random.random((10,2))
X_coords, Y_coords = matrix[:,0], matrix[:,1]
R = np.sqrt(X_coords**2+Y_coords**2)
T = np.arctan2(Y_coords,X_coords)
print(R)
print(T)

[0.84253739 0.52641164 0.59133281 1.00453968 0.96147169 0.60991449
 0.94752003 1.27603248 0.95435925 1.04828507]
[1.23458751 1.40275425 0.58149502 0.203472   1.23740005 0.87965029
 0.71166772 0.72886848 1.35803194 0.71771563]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vector = np.random.random(10)
print(vector)
vector[vector.argmax()] = 0
print(vector)

[0.14641096 0.50324457 0.8407167  0.10391518 0.84454769 0.18422608
 0.02458337 0.28192257 0.04451739 0.24391243]
[0.14641096 0.50324457 0.8407167  0.10391518 0.         0.18422608
 0.02458337 0.28192257 0.04451739 0.24391243]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1, 2, 3, 4])
Y = np.array([5, 6, 7])
C = 1.0 / (X.reshape((-1,1)) - Y)
print(C)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
print("Integer:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(dtype, 'min: ',np.iinfo(dtype).min) 
    print(dtype, 'max: ',np.iinfo(dtype).max)
print("\nFloat:")
for dtype in [np.float32, np.float64]:
    print(dtype, 'min:', np.finfo(dtype).min) 
    print(dtype, 'min:', np.finfo(dtype).max)

Integer:
<class 'numpy.int8'> min:  -128
<class 'numpy.int8'> max:  127
<class 'numpy.int16'> min:  -32768
<class 'numpy.int16'> max:  32767
<class 'numpy.int32'> min:  -2147483648
<class 'numpy.int32'> max:  2147483647
<class 'numpy.int64'> min:  -9223372036854775808
<class 'numpy.int64'> max:  9223372036854775807

Float:
<class 'numpy.float32'> min: -3.4028235e+38
<class 'numpy.float32'> min: 3.4028235e+38
<class 'numpy.float64'> min: -1.7976931348623157e+308
<class 'numpy.float64'> min: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.inf)
arr = np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
scalar = 2.3
vector = np.array([1.2, 3.4, 4.5, 6.7, 2.8])
print("Vector:", vector)
print(f"Scalar: {scalar}")
print(f"Closest value: {vector[np.argmin(np.abs(vector - scalar))]}")

Vector: [1.2 3.4 4.5 6.7 2.8]
Scalar: 2.3
Closest value: 2.8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
array = np.zeros((3,), dtype=[('x', 'float'), ('y', 'float'), ('r', 'int'), ('g', 'int'), ('b','int')])
array['x'] = np.random.rand(3)
array['y'] = np.random.rand(3)
array['r'] = np.random.randint(0, 255, 3)
array['g'] = np.random.randint(0, 255, 3)
array['b'] = np.random.randint(0, 255, 3)
print(array)

[(0.18352454, 0.06128987, 191, 185, 167)
 (0.88201177, 0.14625175, 234, 152, 253)
 (0.84423869, 0.84884633,  86,  39, 227)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
coordinates = np.random.rand(100, 2)
x, y = np.atleast_2d(coordinates[:, 0], coordinates[:, 1])
result = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
print(result)

[[0.         0.89257638 0.83877226 0.396429   0.56487442 0.89119454
  0.70178499 1.18685948 0.68158444 0.74807467 0.78320753 0.6758193
  0.50764008 0.41237111 1.0993519  0.91470188 0.59295606 0.75947476
  0.33448475 0.02899231 0.10498246 0.28099123 0.8342811  0.6602088
  0.20063547 0.72812955 0.55891411 1.10194904 1.13534729 0.5869881
  0.56595824 0.17129138 0.61524368 0.46693915 0.73486087 0.02644854
  0.64193637 0.78429171 0.85751718 0.3346861  0.62409202 0.3831188
  0.99971786 0.2401592  0.64150524 0.55495206 0.56835189 0.54091246
  0.36176109 0.106891   0.13670605 1.0347698  0.78919185 0.55983713
  0.5428958  0.91041408 0.95580684 1.002339   0.93019304 0.26366459
  0.81899131 0.61204282 0.75338068 0.87788968 0.76995313 0.23282247
  0.66323577 0.76055607 0.69866645 0.9653475  1.08673279 0.36359238
  0.84547394 0.7734692  1.03943494 0.66134883 0.77556487 0.89208565
  0.50073778 1.04256116 1.13690932 0.33867943 0.98523405 0.7330051
  0.50750039 0.71524644 0.88167869 0.766218   0.75006

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
float_array = np.array([3.14, 2.718, 1.618], dtype=np.float32)
print("Float:", float_array)
print("Integer:", float_array.astype(int32))

Float: [3.14  2.718 1.618]
Integer: [3 2 1]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
file = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')
data = np.genfromtxt(file, delimiter=",")
print("Data from file:")
print(data)

Data from file:
[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.array([[1, 2, 3]])
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")
    arr = np.array([[1, 2, 3]])

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
arr = 1 * np.exp(-( (d**2) / ( 2.0 * 1**2 ) ))
print(arr)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
size = 5
elements = 3
arr = np.zeros((size,size))
np.put(arr, np.random.choice(range(size*size), elements, replace=False),10)
print (arr)

[[ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [10. 10.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [4, 5, 6, 7]])
row_means = matrix.mean(axis=1, keepdims=True)
result = matrix - row_means
print("Matrix:")
print(matrix)
print("Result:")
print(result)

Matrix:
[[1 2 3 4]
 [4 5 6 7]]
Result:
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
array = np.array([[1, 4, 7],
                  [3, 6, 9],
                  [2, 5, 8]])
n = 2
sorted_array = array[array[:, n].argsort()]
print("array:")
print(array)
print("\nSorted array:")
print(sorted_array)

array:
[[1 4 7]
 [3 6 9]
 [2 5 8]]

Sorted array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr = np.array([[1, 0, 3],
                [0, 0, 0],
                [4, 0, 6]])
print((~arr.any(axis=0)).any())

arr = np.array([[1, 0, 3],
                [4, 1, 6]])
print((~arr.any(axis=0)).any())

True
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
arr = np.array([1, 3, 5, 8, 9])
value = 6
print(arr[np.abs(arr - value).argmin()])

5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3).reshape(1,3)
iterator = np.nditer([A,B,None])
for x,y,z in iterator: 
    z[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name=None):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', None)
arr = NamedArray(np.arange(10), name='NewArray')
print("Name:", arr.name)

Name: NewArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
arr1 = np.array([1, 3, 5, 8, 9])
arr2 = np.random.randint(0,len(arr1),20)
np.add.at(arr1, arr2, 1)
print(arr1)

[ 3 10  9 11 13]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256 
image = np.random.randint(0, 4, (w, h, 3), dtype=np.ubyte) 
reshaped_image = image.reshape((-1, 3))
print("Number of Unique Colors in the Image:", len(np.unique(reshaped_image, axis=0)))

Number of Unique Colors in the Image: 64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr = np.random.randint(1, 10, (2, 3, 4, 5))
print(arr.sum(axis=(-2,-1)))

[[117  94  99]
 [ 91  92 110]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 1, 0, 1, 2, 2])  
unique_indices, counts = np.unique(S, return_counts=True)
means = np.bincount(S, weights=D) / counts
print( D)
print( S)
print("Means:", means)

[1 2 3 4 5 6]
[0 1 0 1 2 2]
Means: [2.  3.  5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
print("A:")
print(A)
print("\nB:")
print(B)
print("\nA x B:")
print(np.dot(A, B))
print("\nDiagonal Elements of the Dot Product:")
print(np.diag(np.dot(A, B)))

A:
[[1 5 6]
 [8 8 8]
 [4 5 3]]

B:
[[6 2 4]
 [2 8 1]
 [8 7 4]]

A x B:
[[ 64  84  33]
 [128 136  72]
 [ 58  69  33]]

Diagonal Elements of the Dot Product:
[ 64 136  33]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
zeros = 2
new = np.zeros(len(vector) + (len(vector)-1)*(zeros))
new[::zeros+1] = vector
print(new)

[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
array_5_5_3 = np.random.randint(1, 10, (5, 5, 3))
array_5_5 = np.random.randint(1, 10, (5, 5))
print("5, 5, 3:")
print(array_5_5_3)
print("\n5, 5 x 5, 5, 3:")
print(array_5_5_3 * np.expand_dims(array_5_5, axis=-1))

5, 5, 3:
[[[2 3 5]
  [3 6 5]
  [7 4 2]
  [5 5 1]
  [8 8 5]]

 [[8 2 5]
  [7 9 6]
  [1 4 2]
  [6 4 4]
  [6 6 5]]

 [[4 8 1]
  [8 4 3]
  [8 3 6]
  [4 3 9]
  [9 5 3]]

 [[3 4 3]
  [1 8 6]
  [9 6 2]
  [1 2 9]
  [1 4 8]]

 [[4 7 2]
  [9 6 8]
  [6 2 7]
  [5 4 6]
  [7 5 8]]]

5, 5 x 5, 5, 3:
[[[18 27 45]
  [21 42 35]
  [21 12  6]
  [40 40  8]
  [16 16 10]]

 [[24  6 15]
  [35 45 30]
  [ 3 12  6]
  [36 24 24]
  [30 30 25]]

 [[ 8 16  2]
  [24 12  9]
  [64 24 48]
  [ 8  6 18]
  [63 35 21]]

 [[12 16 12]
  [ 8 64 48]
  [72 48 16]
  [ 6 12 54]
  [ 3 12 24]]

 [[32 56 16]
  [ 9  6  8]
  [12  4 14]
  [30 24 36]
  [63 45 72]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr)
arr[[0,1]] = arr[[1,0]]
print('\n', arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
triplets = np.random.randint(1, 20, (10, 3, 2)) 
segments = triplets[:, [0, 1, 1, 2], :].reshape(-1, 2)
unique_segments = np.unique(segments, axis=0)
print("Triplets:")
print(triplets)
print("\nUnique segments:")
print(unique_segments)

Triplets:
[[[14  4]
  [11  7]
  [ 5 18]]

 [[18  5]
  [ 9  2]
  [11  7]]

 [[11 17]
  [12  3]
  [15 15]]

 [[19  4]
  [14 11]
  [10 16]]

 [[ 1  7]
  [ 2  6]
  [14 14]]

 [[ 8  3]
  [19  8]
  [12 14]]

 [[ 3 18]
  [14  9]
  [18 15]]

 [[19 17]
  [12  6]
  [ 1 12]]

 [[ 9 11]
  [ 1 19]
  [15 13]]

 [[ 2  3]
  [ 8 18]
  [ 6 17]]]

Unique segments:
[[ 1  7]
 [ 1 12]
 [ 1 19]
 [ 2  3]
 [ 2  6]
 [ 3 18]
 [ 5 18]
 [ 6 17]
 [ 8  3]
 [ 8 18]
 [ 9  2]
 [ 9 11]
 [10 16]
 [11  7]
 [11 17]
 [12  3]
 [12  6]
 [12 14]
 [14  4]
 [14  9]
 [14 11]
 [14 14]
 [15 13]
 [15 15]
 [18  5]
 [18 15]
 [19  4]
 [19  8]
 [19 17]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,2,3,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 2 3 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def sliding_window(arr, window_size):
    cumsum = np.cumsum(arr)
    cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]
    return cumsum[window_size - 1:] / window_size
arr = np.array([3, 6, 2, 8, 4, 7, 1, 5])
window_size = 3
print(arr)
print(sliding_window(arr, window_size))

[3 6 2 8 4 7 1 5]
[3.66666667 5.33333333 4.66666667 6.33333333 4.         4.33333333]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5, 6])
cols = 3
rows = len(Z) - cols + 1
result = np.lib.stride_tricks.as_strided(Z, shape=(rows, cols), strides=(Z.strides[0], Z.strides[0]))
print(Z)
print('\n', result)

[1 2 3 4 5 6]

 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
bool_array = np.array([True, False, True, False])
neg_bool_array = np.logical_not(bool_array)
print("Boolean:", bool_array)
print("Negated boolean:", neg_bool_array)
# /////////////
float_array = np.array([1.5, -2.7, 3.0, -4.2])
neg_float_array =float_array* -1
print("\nFloat Array:", float_array)
print("Negated float:", neg_float_array)

Boolean: [ True False  True False]
Negated boolean: [False  True False  True]

Float Array: [ 1.5 -2.7  3.  -4.2]
Negated float: [-1.5  2.7 -3.   4.2]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance_to_lines(P0, P1, p):
    v = P1 - P0
    w = p - P0
    c1 = np.sum(w * v, axis=1)
    c2 = np.sum(v * v, axis=1)
    b = c1 / c2
    pb = P0 + b[:, np.newaxis] * v
    distances = np.linalg.norm(p - pb, axis=1)
    return distances

P0 = np.array([[1, 2], [3, 4], [5, 6]])
P1 = np.array([[4, 5], [6, 7], [8, 9]])
p = np.array([3, 4])
distances = distance_to_lines(P0, P1, p)
print(distances)

[0. 0. 0.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance_from_points_to_lines(P0, P1, P):
    v = P1 - P0
    P_reshaped = P[:, np.newaxis, :]
    w = P_reshaped - P0
    c1 = np.sum(w * v, axis=2)
    c2 = np.sum(v * v, axis=1)
    b = c1 / c2
    nearest_points = P0[np.newaxis, :, :] + b[:, :, np.newaxis] * v
    distances = np.linalg.norm(nearest_points - P_reshaped, axis=2)
    return distances
P0 = np.array([[1, 1], [2, 3], [4, 5]])  
P1 = np.array([[4, 5], [6, 7], [8, 9]])  
P = np.array([[3, 4], [5, 6]])  
distances = distance_from_points_to_lines(P0, P1, P)
print(distances)

[[0.2 0.  0. ]
 [0.2 0.  0. ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
def extract_subpart(arr, shape, center, fill=0):
    half = np.asarray(shape) // 2
    start = np.maximum(center - half, 0)
    end = np.minimum(center + half + np.mod(shape, 2), arr.shape)
    sub = np.full(shape, fill, dtype=arr.dtype)
    sub_start = np.maximum(half - center, 0)
    sub_end = shape - np.maximum(center + half - arr.shape, 0)
    sub[sub_start[0]:sub_end[0], sub_start[1]:sub_end[1]] = \
arr[start[0]:end[0], start[1]:end[1]]
    return sub
arr = np.random.randint(1, 10, (6, 7))
subpart_shape = (3, 3)
center_point = (3, 5)
result = extract_subpart(arr, subpart_shape, center_point)
print(arr)
print('\n', result)

[[9 8 3 4 3 4 5]
 [1 5 8 7 7 2 3]
 [8 9 1 3 7 8 6]
 [5 2 8 8 4 4 6]
 [6 4 2 2 1 8 4]
 [7 4 1 6 3 4 3]]

 [[7 8 6]
 [4 4 6]
 [1 8 4]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)
print("\nRank:", np.linalg.matrix_rank(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


#### 83. How to find the most frequent value in an array?

In [ ]:
arr = np.array([1, 3, 5, 3, 7, 5, 3, 7, 5, 9, 5])
print( arr)
print("Most frequent value:",np.bincount(arr).argmax())

[1 3 5 3 7 5 3 7 5 9 5]
Most frequent value: 5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
matrix = np.random.randint(0, 10, (10, 10))
blocks = [matrix[i:i+3, j:j+3] for i in range(8) for j in range(8)]
for block in blocks:
    print(block, "\n")

[[1 6 9]
 [6 8 0]
 [5 9 0]] 

[[6 9 3]
 [8 0 9]
 [9 0 6]] 

[[9 3 1]
 [0 9 2]
 [0 6 1]] 

[[3 1 1]
 [9 2 9]
 [6 1 6]] 

[[1 1 8]
 [2 9 0]
 [1 6 4]] 

[[1 8 4]
 [9 0 5]
 [6 4 6]] 

[[8 4 9]
 [0 5 1]
 [4 6 4]] 

[[4 9 8]
 [5 1 5]
 [6 4 5]] 

[[6 8 0]
 [5 9 0]
 [5 4 1]] 

[[8 0 9]
 [9 0 6]
 [4 1 9]] 

[[0 9 2]
 [0 6 1]
 [1 9 6]] 

[[9 2 9]
 [6 1 6]
 [9 6 4]] 

[[2 9 0]
 [1 6 4]
 [6 4 4]] 

[[9 0 5]
 [6 4 6]
 [4 4 1]] 

[[0 5 1]
 [4 6 4]
 [4 1 6]] 

[[5 1 5]
 [6 4 5]
 [1 6 1]] 

[[5 9 0]
 [5 4 1]
 [5 4 5]] 

[[9 0 6]
 [4 1 9]
 [4 5 5]] 

[[0 6 1]
 [1 9 6]
 [5 5 3]] 

[[6 1 6]
 [9 6 4]
 [5 3 9]] 

[[1 6 4]
 [6 4 4]
 [3 9 2]] 

[[6 4 6]
 [4 4 1]
 [9 2 0]] 

[[4 6 4]
 [4 1 6]
 [2 0 6]] 

[[6 4 5]
 [1 6 1]
 [0 6 9]] 

[[5 4 1]
 [5 4 5]
 [3 9 8]] 

[[4 1 9]
 [4 5 5]
 [9 8 3]] 

[[1 9 6]
 [5 5 3]
 [8 3 1]] 

[[9 6 4]
 [5 3 9]
 [3 1 8]] 

[[6 4 4]
 [3 9 2]
 [1 8 3]] 

[[4 4 1]
 [9 2 0]
 [8 3 5]] 

[[4 1 6]
 [2 0 6]
 [3 5 9]] 

[[1 6 1]
 [0 6 9]
 [5 9 4]] 

[[5 4 5]
 [3 9 8]
 [2 3 5]] 

[[4 5 5]
 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class SymmetricArray(np.ndarray):
    def __new__(cls, shape, dtype=int):
        return np.zeros(shape, dtype=dtype).view(cls)
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)
Z = SymmetricArray((3, 3), dtype=int)
Z[0, 1] = 3
Z[1, 2] = 5
print(Z)

[[0 3 0]
 [3 0 5]
 [0 5 0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p = 3
n = 4
matrices = np.random.randint(1, 10, size=(p, n, n))
vectors = np.random.randint(1, 10, size=(p, n, 1))  
print(np.tensordot(matrices, vectors, axes=[[0, 2], [0, 1]]))

[[312]
 [352]
 [218]
 [378]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array = np.random.randint(1, 10, (16, 16))
block_size = 4
reshaped_array = array.reshape(4, 4, 4, 4)
print(array)
print("\n", reshaped_array.sum(axis=(2, 3)))

[[6 9 4 5 1 2 1 9 8 2 4 5 8 4 4 5]
 [5 2 2 4 1 9 3 6 9 4 1 5 4 2 1 8]
 [1 5 4 5 6 9 3 6 1 5 9 4 7 1 5 5]
 [2 2 1 7 8 9 8 5 2 7 7 1 6 5 8 5]
 [6 5 7 2 6 1 2 2 2 5 7 1 5 7 3 3]
 [1 8 7 7 8 5 1 2 4 9 3 8 7 7 5 1]
 [7 8 7 1 8 8 1 1 3 5 9 1 9 9 9 8]
 [5 4 7 6 9 2 5 7 4 5 4 6 8 9 4 3]
 [9 4 9 6 5 2 2 5 4 3 1 3 8 3 7 5]
 [8 5 1 3 6 4 3 3 2 3 5 7 9 1 4 7]
 [9 8 2 3 2 6 5 2 1 9 7 8 9 7 3 8]
 [7 9 9 5 6 9 6 3 6 2 4 3 8 1 7 8]
 [7 1 3 2 7 7 6 2 4 5 3 3 9 9 3 2]
 [9 2 8 2 9 5 8 9 7 4 5 5 3 9 9 3]
 [3 3 9 9 7 3 6 5 1 9 5 9 9 4 1 2]
 [9 6 9 6 6 1 4 5 8 2 3 5 1 8 1 6]]

 [[77 66 76 83]
 [64 83 94 88]
 [76 71 89 93]
 [73 97 85 80]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(grid):
    N = (grid[0:-2,0:-2] + grid[0:-2,1:-1] + grid[0:-2,2:] +
         grid[1:-1,0:-2]                + grid[1:-1,2:] +
         grid[2:  ,0:-2] + grid[2:  ,1:-1] + grid[2:  ,2:])

    birth = (N==3) & (grid[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (grid[1:-1,1:-1]==1)
    grid.fill(0)
    grid[1:-1,1:-1][birth | survive] = 1
    return grid

grid = np.random.randint(0, 2, (50, 50))
for i in range(100):
    grid = iterate(grid)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
arr = np.array([3, 1, 7, 12, 9, 4, 8, 6])
n = 3
print(arr[np.argpartition(arr, -n)[-n:]])

[ 8  9 12]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
vector1 = np.array([1, 2, 3])
vector2 = np.array(['a', 'b'])
vector3 = np.array([True, False])
result = np.array(np.meshgrid(vector1, vector2, vector3)).T.reshape(-1, len([vector1, vector2, vector3]))
print(result)

[['1' 'a' 'True']
 ['1' 'b' 'True']
 ['2' 'a' 'True']
 ['2' 'b' 'True']
 ['3' 'a' 'True']
 ['3' 'b' 'True']
 ['1' 'a' 'False']
 ['1' 'b' 'False']
 ['2' 'a' 'False']
 ['2' 'b' 'False']
 ['3' 'a' 'False']
 ['3' 'b' 'False']]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
array = np.array([(1, 2.0, 'Hello'), (3, 4.0, 'World')],
                         dtype=[('x', int), ('y', float), ('z', 'U10')])

record_array = np.core.records.fromarrays((array['x'], array['y'], array['z']),
                                          dtype=array.dtype)

print(record_array)

[(1, 2., 'Hello') (3, 4., 'World')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.random.rand(1000000)
method_1 = Z ** 3
# ///////
method_2 = np.power(Z, 3)
# ////////////
method_3 = Z * Z * Z

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0, 5, (8, 3))
B = np.array([[1, 2], [3, -1]])
el = (A[..., np.newaxis, np.newaxis] == B)
rows = (el.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
matrix = np.random.randint(0, 4, (10, 3))
unequal = matrix[~(np.all(matrix[:, 1:] == matrix[:, :-1], axis=1))]
print(matrix)
print('\n', unequal)

[[1 3 2]
 [0 3 1]
 [0 2 3]
 [0 0 1]
 [1 3 0]
 [0 3 0]
 [0 0 0]
 [2 1 2]
 [2 1 3]
 [3 2 1]]

 [[1 3 2]
 [0 3 1]
 [0 2 3]
 [0 0 1]
 [1 3 0]
 [0 3 0]
 [2 1 2]
 [2 1 3]
 [3 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
vector = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(vector[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
arr = np.array([[1, 2, 3],
                     [4, 2, 6],
                     [1, 2, 3],
                     [7, 8, 9],
                     [4, 2, 6]])
print(arr)
print("Unique rows:")
print(np.unique(arr, axis=0))

[[1 2 3]
 [4 2 6]
 [1 2 3]
 [7 8 9]
 [4 2 6]]
Unique rows:
[[1 2 3]
 [4 2 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_product = np.einsum('i,i->', A, B)
outer_product = np.einsum('i,j->ij', A, B)
sum = np.einsum('i,j->', A, B) 
mul = np.einsum('i,i->i', A, B)
print("Inner product:", inner_product)
print("Outer product:\n", outer_product)
print("A + B:", sum)
print("Multiplication:", mul)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
A + B: 90
Multiplication: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
X = np.array([0, 2, 3, 5, 7])
Y = np.array([1, 3, 4, 6, 8])
dif_X = np.diff(X)
dif_Y = np.diff(Y)
distances = np.sqrt(dif_X ** 2 + dif_Y ** 2)
total_distance = np.sum(distances)
num_samples = 10

steps = np.linspace(0, total_distance, num_samples)
sampled_X = np.zeros(num_samples)
sampled_Y = np.zeros(num_samples)
for i, step in enumerate(steps):
    segment = np.searchsorted(np.cumsum(distances), step)
    if segment == 0:
        fr = step / total_distance
    else:
        fraction = (step - np.sum(distances[:segment])) / distances[segment - 1]
    sampled_X[i] = X[segment] + fr * dif_X[segment - 1]
    sampled_Y[i] = Y[segment] + fr * dif_Y[segment - 1]
print("X:", sampled_X)
print("Y:", sampled_Y)


X: [0.         0.22222222 0.44444444 2.44444444 3.22222222 3.22222222
 3.22222222 5.44444444 5.44444444 5.44444444]
Y: [1.         1.22222222 1.44444444 3.44444444 4.22222222 4.22222222
 4.22222222 6.44444444 6.44444444 6.44444444]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
n = 5
X = np.array([[1, 2, 2],
              [0, 3, 4],
              [5, 0, 0],
              [2, 3, 0]])
rows = X[(X.sum(axis=1) == n)]
print(rows)

[[1 2 2]
 [5 0 0]
 [2 3 0]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
np.random.seed(42)
X = np.random.normal(loc=10, scale=2, size=100)
N = 1000
means = [np.mean(np.random.choice(X, len(X), replace=True)) for _ in range(N)]
print(np.percentile(means, [2.5, 97.5]))

[ 9.45532715 10.12570297]
